export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const START_FETCHING_COMMENTS = 'START_FETCHING_COMMENTS';
export const FINISH_FETCHING_COMMENTS = 'FINISH_FETCHING_COMMENTS';
export const SAVE_COMMENT_TO_POST = 'SAVE_COMMENT_TO_POST';

export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const SEND_COMMENTS = 'SEND_COMMENTS';
